#!/bin/bash
declare -a HuntressDaemons=("HuntressAgent" "HuntressUpdater" "Huntress")

# Check if the daemons are running as expected
daemons_running=true
for i in "${HuntressDaemons[@]}"; do 
  pgrep -x "$i" >/dev/null
  daemon_status=$?
  if [ "$daemon_status" != "0" ]; then
    echo "No - Service $i is not running"
    daemons_running=false
  fi
done;

if $daemons_running; then 
  echo "Yes - All Huntress services running" 
fi;

# Application Support Directory present
if [ -d "/Library/Application Support/Huntress" ]; then
    echo "Yes - Installed"
else
    echo "No - Not Installed"
fi

# Check if agent has FDA
# TBD - it'd be good to leverage Wizard in the future

# Check system extension status
output=$(/Applications/Huntress.app/Contents/MacOS/Huntress extensionctl status)

# Check if extension installed
if [[ $output == *"Extension Status: installed"* ]]; then
  echo "Yes - Extension Installed";
else
  echo "No - Extension Not Installed";
fi

if [[ $output == *"Full Disk Access for Extension: enabled"* ]]; then
  echo "Yes - Full Disk Access granted for Extension";
else
  echo "No - Full Disk Access not granted for Extension"
fi;

if [[ $output == *"EDR: enabled"* ]]; then
  echo "Yes - EDR Enabled"
else
  echo "No - EDR is not Enabled"
fi;

if [[ $output == *"Preauthorization Status: granted"* ]]; then
  echo "Yes - Preauthorization granted"
else
  echo "No - Preauthorization not granted"
fi

